using System;
using System.Collections.Generic;
using Covenants.Common;
using Covenants.DAL.Interfaces;
using Covenants.Models;

namespace Covenants.BLL.Services
{
    // -----------------------------------------------------------------------
    // FOLLOW-UP SERVICE — LIFECYCLE MANAGEMENT FOR COVENANT FOLLOW-UPS
    // -----------------------------------------------------------------------
    // A CovenantFollowUp is a task that tracks work done against a covenant.
    // Follow-ups can be:
    //   - MANUAL: a user clicks "Add Follow-Up" on the Details page.
    //   - AUTO:   the SchedulerEngine fires and calls CreateAutoFollowUp().
    //
    // LIFECYCLE (status flow):
    //   Pending → InProgress → Completed      (finished before EndDate)
    //                        → CompletedLate  (finished after EndDate)
    //          → Cancelled                    (discarded without completion)
    //
    // Business rules enforced here (not in the UI or DAL):
    //   - Only Pending follow-ups can be Started.
    //   - Already-closed follow-ups (Completed, CompletedLate, Cancelled) cannot be re-closed.
    //   - Completing after EndDate automatically sets status to CompletedLate.
    //   - Completed follow-ups cannot be cancelled (use Complete, not Cancel).
    // -----------------------------------------------------------------------

    public class FollowUpService
    {
        private readonly ICovenantFollowUpRepository _repo;
        private readonly HistoryService _history;

        public FollowUpService(ICovenantFollowUpRepository repo, HistoryService history)
        {
            _repo    = repo;
            _history = history;
        }

        // -------------------------------------------------------------------
        // READ — simple pass-throughs
        // -------------------------------------------------------------------
        public IEnumerable<CovenantFollowUp> GetByCovenant(int covenantId) =>
            _repo.GetByCovenantId(covenantId);

        public CovenantFollowUp GetById(int id) => _repo.GetById(id);

        // -------------------------------------------------------------------
        // CREATE — Manual follow-up (user-initiated from the Details page)
        // -------------------------------------------------------------------
        public Result<int> Create(CovenantFollowUp followUp, string createdBy)
        {
            try
            {
                followUp.CreatedBy = createdBy;
                // Always starts in Pending state — the user must click Start
                followUp.Status    = Constants.FollowUpStatuses.Pending;

                int id = _repo.Insert(followUp);

                // Record in audit trail — the History tab on the Details page will show this
                _history.Write(followUp.CovenantId, Constants.HistoryActions.FollowUpAdded, createdBy,
                    notes: $"Follow-up '{followUp.Title}' added (manual).");

                return Result<int>.Ok(id);
            }
            catch (Exception ex)
            {
                return Result<int>.Fail(ex.Message);
            }
        }

        // -------------------------------------------------------------------
        // CREATE — Auto follow-up (triggered by SchedulerEngine)
        // -------------------------------------------------------------------
        /// <summary>
        /// Called by the SchedulerEngine when a schedule's NextRunAt is reached.
        /// Automatically creates a Pending follow-up linked to the schedule.
        /// </summary>
        /// <param name="schedule">The schedule that just fired.</param>
        /// <param name="systemUser">Written as CreatedBy (defaults to "SYSTEM").</param>
        public Result<int> CreateAutoFollowUp(CovenantSchedule schedule, string systemUser = "SYSTEM")
        {
            try
            {
                var followUp = new CovenantFollowUp
                {
                    CovenantId      = schedule.CovenantId,
                    ScheduleId      = schedule.Id,            // links back to the schedule that triggered it
                    Title           = $"Scheduled follow-up ({schedule.ScheduleType}) – {DateTime.UtcNow:d}",
                    StartDate       = DateTime.UtcNow,
                    // If the schedule has an EndDate, use it as the follow-up deadline;
                    // otherwise give the user 7 days to act
                    EndDate         = schedule.EndDate ?? DateTime.UtcNow.AddDays(7),
                    Status          = Constants.FollowUpStatuses.Pending,
                    IsAutoGenerated = true,                   // flag so UI can distinguish auto vs manual
                    CreatedBy       = systemUser
                };

                int id = _repo.Insert(followUp);

                _history.Write(schedule.CovenantId, Constants.HistoryActions.FollowUpAdded, systemUser,
                    notes: $"Auto follow-up created by scheduler (Schedule #{schedule.Id}).");

                return Result<int>.Ok(id);
            }
            catch (Exception ex)
            {
                return Result<int>.Fail(ex.Message);
            }
        }

        // -------------------------------------------------------------------
        // START — Pending → InProgress
        // -------------------------------------------------------------------
        public Result Start(int id, string startedBy)
        {
            try
            {
                var fu = _repo.GetById(id);
                if (fu == null) return Result.Fail("Follow-up not found.");

                // BUSINESS RULE: can only start a Pending follow-up.
                // Already-started or completed ones are unchanged.
                if (fu.Status != Constants.FollowUpStatuses.Pending)
                    return Result.Fail("Only Pending follow-ups can be started.");

                // Repository sets Status=InProgress, StartedAt=GETUTCDATE(), StartedBy=@user
                _repo.Start(id, startedBy);
                return Result.Ok();
            }
            catch (Exception ex)
            {
                return Result.Fail(ex.Message);
            }
        }

        // -------------------------------------------------------------------
        // COMPLETE — InProgress (or Pending) → Completed / CompletedLate
        // -------------------------------------------------------------------
        public Result Complete(int id, string completedBy, string completionNotes)
        {
            try
            {
                var fu = _repo.GetById(id);
                if (fu == null) return Result.Fail("Follow-up not found.");

                // BUSINESS RULE: cannot complete something already closed
                if (fu.Status == Constants.FollowUpStatuses.Completed     ||
                    fu.Status == Constants.FollowUpStatuses.CompletedLate  ||
                    fu.Status == Constants.FollowUpStatuses.Cancelled)
                    return Result.Fail("Follow-up is already closed.");

                // KEY RULE: if we complete after the EndDate deadline → CompletedLate.
                // DateTime.UtcNow > fu.EndDate means we're past the due date.
                // The DB also has an IsOverdue computed column, but we set the STATUS here
                // so the record permanently reflects whether it was completed late.
                string status = DateTime.UtcNow > fu.EndDate
                    ? Constants.FollowUpStatuses.CompletedLate
                    : Constants.FollowUpStatuses.Completed;

                // Repository sets CompletedAt=now, CompletedBy, CompletionNotes, and Status
                _repo.Complete(id, completedBy, completionNotes, status);
                return Result.Ok();
            }
            catch (Exception ex)
            {
                return Result.Fail(ex.Message);
            }
        }

        // -------------------------------------------------------------------
        // CANCEL — any open status → Cancelled
        // -------------------------------------------------------------------
        public Result Cancel(int id, string cancelledBy)
        {
            try
            {
                var fu = _repo.GetById(id);
                if (fu == null) return Result.Fail("Follow-up not found.");

                // BUSINESS RULE: cannot cancel something that is already done.
                // (If they want to undo a completion, that's a different workflow.)
                if (fu.Status == Constants.FollowUpStatuses.Completed     ||
                    fu.Status == Constants.FollowUpStatuses.CompletedLate)
                    return Result.Fail("Cannot cancel an already completed follow-up.");

                _repo.Cancel(id, cancelledBy);
                return Result.Ok();
            }
            catch (Exception ex)
            {
                return Result.Fail(ex.Message);
            }
        }
    }
}
