using System;
using System.Collections.Generic;
using Covenants.Common;
using Covenants.DAL.Interfaces;
using Covenants.Models;

namespace Covenants.BLL.Services
{
    public class FollowUpService
    {
        private readonly ICovenantFollowUpRepository _repo;
        private readonly HistoryService _history;

        public FollowUpService(ICovenantFollowUpRepository repo, HistoryService history)
        {
            _repo    = repo;
            _history = history;
        }

        public IEnumerable<CovenantFollowUp> GetByCovenant(int covenantId) =>
            _repo.GetByCovenantId(covenantId);

        public CovenantFollowUp GetById(int id) => _repo.GetById(id);

        public Result<int> Create(CovenantFollowUp followUp, string createdBy)
        {
            try
            {
                followUp.CreatedBy = createdBy;
                followUp.Status    = Constants.FollowUpStatuses.Pending;
                int id = _repo.Insert(followUp);
                _history.Write(followUp.CovenantId, Constants.HistoryActions.FollowUpAdded, createdBy,
                    notes: $"Follow-up '{followUp.Title}' added (manual).");
                return Result<int>.Ok(id);
            }
            catch (Exception ex)
            {
                return Result<int>.Fail(ex.Message);
            }
        }

        /// <summary>Auto-creates a follow-up from a scheduled trigger.</summary>
        public Result<int> CreateAutoFollowUp(CovenantSchedule schedule, string systemUser = "SYSTEM")
        {
            try
            {
                var followUp = new CovenantFollowUp
                {
                    CovenantId      = schedule.CovenantId,
                    ScheduleId      = schedule.Id,
                    Title           = $"Scheduled follow-up ({schedule.ScheduleType}) – {DateTime.UtcNow:d}",
                    StartDate       = DateTime.UtcNow,
                    EndDate         = schedule.EndDate ?? DateTime.UtcNow.AddDays(7),
                    Status          = Constants.FollowUpStatuses.Pending,
                    IsAutoGenerated = true,
                    CreatedBy       = systemUser
                };

                int id = _repo.Insert(followUp);
                _history.Write(schedule.CovenantId, Constants.HistoryActions.FollowUpAdded, systemUser,
                    notes: $"Auto follow-up created by scheduler (Schedule #{schedule.Id}).");
                return Result<int>.Ok(id);
            }
            catch (Exception ex)
            {
                return Result<int>.Fail(ex.Message);
            }
        }

        public Result Start(int id, string startedBy)
        {
            try
            {
                var fu = _repo.GetById(id);
                if (fu == null) return Result.Fail("Follow-up not found.");
                if (fu.Status != Constants.FollowUpStatuses.Pending)
                    return Result.Fail("Only Pending follow-ups can be started.");

                _repo.Start(id, startedBy);
                return Result.Ok();
            }
            catch (Exception ex)
            {
                return Result.Fail(ex.Message);
            }
        }

        public Result Complete(int id, string completedBy, string completionNotes)
        {
            try
            {
                var fu = _repo.GetById(id);
                if (fu == null) return Result.Fail("Follow-up not found.");
                if (fu.Status == Constants.FollowUpStatuses.Completed ||
                    fu.Status == Constants.FollowUpStatuses.CompletedLate ||
                    fu.Status == Constants.FollowUpStatuses.Cancelled)
                    return Result.Fail("Follow-up is already closed.");

                // Determine late vs on-time
                string status = DateTime.UtcNow > fu.EndDate
                    ? Constants.FollowUpStatuses.CompletedLate
                    : Constants.FollowUpStatuses.Completed;

                _repo.Complete(id, completedBy, completionNotes, status);
                return Result.Ok();
            }
            catch (Exception ex)
            {
                return Result.Fail(ex.Message);
            }
        }

        public Result Cancel(int id, string cancelledBy)
        {
            try
            {
                var fu = _repo.GetById(id);
                if (fu == null) return Result.Fail("Follow-up not found.");
                if (fu.Status == Constants.FollowUpStatuses.Completed ||
                    fu.Status == Constants.FollowUpStatuses.CompletedLate)
                    return Result.Fail("Cannot cancel an already completed follow-up.");

                _repo.Cancel(id, cancelledBy);
                return Result.Ok();
            }
            catch (Exception ex)
            {
                return Result.Fail(ex.Message);
            }
        }
    }
}
