using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using Covenants.Common;
using Covenants.DAL.Interfaces;
using Covenants.Models;

namespace Covenants.DAL.Repositories
{
    public class CovenantFollowUpRepository : ICovenantFollowUpRepository
    {
        private const string SelectAll = @"
            SELECT Id, CovenantId, ScheduleId, Title, Description,
                   StartDate, EndDate, Status, Notes, CompletionNotes,
                   StartedAt, StartedBy, CompletedAt, CompletedBy,
                   IsAutoGenerated, IsOverdue,
                   CreatedAt, CreatedBy, UpdatedAt, UpdatedBy
            FROM CovenantFollowUps";

        public IEnumerable<CovenantFollowUp> GetByCovenantId(int covenantId)
        {
            var list = new List<CovenantFollowUp>();
            using (var conn = ConnectionFactory.Create())
            using (var cmd = new SqlCommand($"{SelectAll} WHERE CovenantId = @CovenantId ORDER BY EndDate ASC", conn))
            {
                cmd.Parameters.AddWithValue("@CovenantId", covenantId);
                conn.Open();
                using (var r = cmd.ExecuteReader())
                    while (r.Read()) list.Add(Map(r));
            }
            return list;
        }

        public CovenantFollowUp GetById(int id)
        {
            using (var conn = ConnectionFactory.Create())
            using (var cmd = new SqlCommand($"{SelectAll} WHERE Id = @Id", conn))
            {
                cmd.Parameters.AddWithValue("@Id", id);
                conn.Open();
                using (var r = cmd.ExecuteReader())
                    return r.Read() ? Map(r) : null;
            }
        }

        public int Insert(CovenantFollowUp f)
        {
            using (var conn = ConnectionFactory.Create())
            using (var cmd = new SqlCommand(@"
                INSERT INTO CovenantFollowUps
                    (CovenantId, ScheduleId, Title, Description, StartDate, EndDate,
                     Status, Notes, IsAutoGenerated, CreatedAt, CreatedBy)
                VALUES
                    (@CovenantId, @ScheduleId, @Title, @Description, @StartDate, @EndDate,
                     @Status, @Notes, @IsAutoGenerated, GETUTCDATE(), @CreatedBy);
                SELECT SCOPE_IDENTITY();", conn))
            {
                cmd.Parameters.AddWithValue("@CovenantId",      f.CovenantId);
                cmd.Parameters.AddWithValue("@ScheduleId",      (object)f.ScheduleId      ?? DBNull.Value);
                cmd.Parameters.AddWithValue("@Title",           f.Title);
                cmd.Parameters.AddWithValue("@Description",     (object)f.Description     ?? DBNull.Value);
                cmd.Parameters.AddWithValue("@StartDate",       f.StartDate);
                cmd.Parameters.AddWithValue("@EndDate",         f.EndDate);
                cmd.Parameters.AddWithValue("@Status",          f.Status ?? Constants.FollowUpStatuses.Pending);
                cmd.Parameters.AddWithValue("@Notes",           (object)f.Notes           ?? DBNull.Value);
                cmd.Parameters.AddWithValue("@IsAutoGenerated", f.IsAutoGenerated);
                cmd.Parameters.AddWithValue("@CreatedBy",       (object)f.CreatedBy       ?? DBNull.Value);
                conn.Open();
                return Convert.ToInt32(cmd.ExecuteScalar());
            }
        }

        public void Update(CovenantFollowUp f)
        {
            using (var conn = ConnectionFactory.Create())
            using (var cmd = new SqlCommand(@"
                UPDATE CovenantFollowUps
                SET Title       = @Title,
                    Description = @Description,
                    StartDate   = @StartDate,
                    EndDate     = @EndDate,
                    Notes       = @Notes,
                    UpdatedAt   = GETUTCDATE(),
                    UpdatedBy   = @UpdatedBy
                WHERE Id = @Id", conn))
            {
                cmd.Parameters.AddWithValue("@Title",       f.Title);
                cmd.Parameters.AddWithValue("@Description", (object)f.Description ?? DBNull.Value);
                cmd.Parameters.AddWithValue("@StartDate",   f.StartDate);
                cmd.Parameters.AddWithValue("@EndDate",     f.EndDate);
                cmd.Parameters.AddWithValue("@Notes",       (object)f.Notes       ?? DBNull.Value);
                cmd.Parameters.AddWithValue("@UpdatedBy",   (object)f.UpdatedBy   ?? DBNull.Value);
                cmd.Parameters.AddWithValue("@Id",          f.Id);
                conn.Open();
                cmd.ExecuteNonQuery();
            }
        }

        public void UpdateStatus(int id, string status, string updatedBy)
        {
            using (var conn = ConnectionFactory.Create())
            using (var cmd = new SqlCommand(@"
                UPDATE CovenantFollowUps
                SET Status = @Status, UpdatedAt = GETUTCDATE(), UpdatedBy = @UpdatedBy
                WHERE Id = @Id", conn))
            {
                cmd.Parameters.AddWithValue("@Status",    status);
                cmd.Parameters.AddWithValue("@UpdatedBy", (object)updatedBy ?? DBNull.Value);
                cmd.Parameters.AddWithValue("@Id",        id);
                conn.Open();
                cmd.ExecuteNonQuery();
            }
        }

        public void Start(int id, string startedBy)
        {
            using (var conn = ConnectionFactory.Create())
            using (var cmd = new SqlCommand(@"
                UPDATE CovenantFollowUps
                SET Status    = 'InProgress',
                    StartedAt = GETUTCDATE(),
                    StartedBy = @StartedBy,
                    UpdatedAt = GETUTCDATE(),
                    UpdatedBy = @StartedBy
                WHERE Id = @Id", conn))
            {
                cmd.Parameters.AddWithValue("@StartedBy", (object)startedBy ?? DBNull.Value);
                cmd.Parameters.AddWithValue("@Id", id);
                conn.Open();
                cmd.ExecuteNonQuery();
            }
        }

        public void Complete(int id, string completedBy, string completionNotes, string status)
        {
            using (var conn = ConnectionFactory.Create())
            using (var cmd = new SqlCommand(@"
                UPDATE CovenantFollowUps
                SET Status          = @Status,
                    CompletedAt     = GETUTCDATE(),
                    CompletedBy     = @CompletedBy,
                    CompletionNotes = @CompletionNotes,
                    UpdatedAt       = GETUTCDATE(),
                    UpdatedBy       = @CompletedBy
                WHERE Id = @Id", conn))
            {
                cmd.Parameters.AddWithValue("@Status",          status);
                cmd.Parameters.AddWithValue("@CompletedBy",     (object)completedBy     ?? DBNull.Value);
                cmd.Parameters.AddWithValue("@CompletionNotes", (object)completionNotes ?? DBNull.Value);
                cmd.Parameters.AddWithValue("@Id",              id);
                conn.Open();
                cmd.ExecuteNonQuery();
            }
        }

        public void Cancel(int id, string updatedBy)
        {
            using (var conn = ConnectionFactory.Create())
            using (var cmd = new SqlCommand(@"
                UPDATE CovenantFollowUps
                SET Status = 'Cancelled', UpdatedAt = GETUTCDATE(), UpdatedBy = @UpdatedBy
                WHERE Id = @Id", conn))
            {
                cmd.Parameters.AddWithValue("@UpdatedBy", (object)updatedBy ?? DBNull.Value);
                cmd.Parameters.AddWithValue("@Id", id);
                conn.Open();
                cmd.ExecuteNonQuery();
            }
        }

        private static CovenantFollowUp Map(SqlDataReader r) => new CovenantFollowUp
        {
            Id              = r.GetInt32(r.GetOrdinal("Id")),
            CovenantId      = r.GetInt32(r.GetOrdinal("CovenantId")),
            ScheduleId      = r.IsDBNull(r.GetOrdinal("ScheduleId"))      ? (int?)null    : r.GetInt32(r.GetOrdinal("ScheduleId")),
            Title           = r.GetString(r.GetOrdinal("Title")),
            Description     = r.IsDBNull(r.GetOrdinal("Description"))     ? null           : r.GetString(r.GetOrdinal("Description")),
            StartDate       = r.GetDateTime(r.GetOrdinal("StartDate")),
            EndDate         = r.GetDateTime(r.GetOrdinal("EndDate")),
            Status          = r.GetString(r.GetOrdinal("Status")),
            Notes           = r.IsDBNull(r.GetOrdinal("Notes"))           ? null           : r.GetString(r.GetOrdinal("Notes")),
            CompletionNotes = r.IsDBNull(r.GetOrdinal("CompletionNotes")) ? null           : r.GetString(r.GetOrdinal("CompletionNotes")),
            StartedAt       = r.IsDBNull(r.GetOrdinal("StartedAt"))       ? (DateTime?)null : r.GetDateTime(r.GetOrdinal("StartedAt")),
            StartedBy       = r.IsDBNull(r.GetOrdinal("StartedBy"))       ? null           : r.GetString(r.GetOrdinal("StartedBy")),
            CompletedAt     = r.IsDBNull(r.GetOrdinal("CompletedAt"))     ? (DateTime?)null : r.GetDateTime(r.GetOrdinal("CompletedAt")),
            CompletedBy     = r.IsDBNull(r.GetOrdinal("CompletedBy"))     ? null           : r.GetString(r.GetOrdinal("CompletedBy")),
            IsAutoGenerated = r.GetBoolean(r.GetOrdinal("IsAutoGenerated")),
            IsOverdue       = r.GetBoolean(r.GetOrdinal("IsOverdue")),
            CreatedAt       = r.GetDateTime(r.GetOrdinal("CreatedAt")),
            CreatedBy       = r.IsDBNull(r.GetOrdinal("CreatedBy"))       ? null           : r.GetString(r.GetOrdinal("CreatedBy")),
            UpdatedAt       = r.IsDBNull(r.GetOrdinal("UpdatedAt"))       ? (DateTime?)null : r.GetDateTime(r.GetOrdinal("UpdatedAt")),
            UpdatedBy       = r.IsDBNull(r.GetOrdinal("UpdatedBy"))       ? null           : r.GetString(r.GetOrdinal("UpdatedBy"))
        };
    }
}
