using System;

namespace Covenants.Models
{
    public class CovenantFollowUp
    {
        public int Id { get; set; }
        public int CovenantId { get; set; }
        public int? ScheduleId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public string Status { get; set; }          // Pending | InProgress | Completed | CompletedLate | Cancelled
        public string Notes { get; set; }
        public string CompletionNotes { get; set; }
        public DateTime? StartedAt { get; set; }
        public string StartedBy { get; set; }
        public DateTime? CompletedAt { get; set; }
        public string CompletedBy { get; set; }
        public bool IsAutoGenerated { get; set; }
        public bool IsOverdue { get; set; }         // computed column from DB
        public DateTime CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
    }
}
